<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_Parent" Id="{291b6a94-190c-4903-85c0-ad087a0adcde}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Parent
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	ref_child : REFERENCE TO FB_Child;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_Parent">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>